import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const agentConfig = await readFile(new URL("../.codex/agents/design-reviewer.toml", import.meta.url), "utf8")
const repositoryInstructions = await readFile(new URL("../AGENTS.md", import.meta.url), "utf8")
const mainDeveloperRole = await readFile(new URL("../docs/MAIN_DEVELOPER_ROLE.md", import.meta.url), "utf8")
const designReviewRole = await readFile(new URL("../docs/DESIGN_REVIEW_AGENT.md", import.meta.url), "utf8")
const designReviewChecklist = await readFile(new URL("../docs/DESIGN_REVIEW_CHECKLIST.md", import.meta.url), "utf8")

test("영구 디자인 전문 검토 에이전트의 읽기 전용·단일 기준 계약을 유지한다", () => {
  assert.match(agentConfig, /^name = "design_reviewer"$/m)
  assert.match(agentConfig, /^sandbox_mode = "read-only"$/m)
  assert.match(agentConfig, /^model_reasoning_effort = "high"$/m)
  assert.doesNotMatch(agentConfig, /^model = /m)
  assert.match(agentConfig, /코드, 설정, 문서와 테스트를 수정하지 않는다/)
  assert.match(agentConfig, /docs\/DESIGN_REVIEW_AGENT\.md의 "검토 절차"를 단일 기준으로 따른다/)
  assert.match(agentConfig, /docs\/DESIGN_REVIEW_CHECKLIST\.md를 따른다/)
  assert.match(agentConfig, /메인 개발자가 제공한 검수 브리프/)
  assert.match(agentConfig, /범위 검수는 브리프가 지정한 요구사항·UI\/UX 기준 절과 체크리스트 항목만/)
  assert.match(agentConfig, /전체 검수에서만 docs\/PROJECT_GOALS\.md/)
  assert.match(agentConfig, /저장소 보고서는 직접 만들지 않고 구조화된 결과를 메인 개발자에게 반환한다/)
})

test("작업 규모별 검증과 독립 디자인 게이트의 핵심 안전 경계를 유지한다", () => {
  assert.match(repositoryInstructions, /`작업 완료`/)
  assert.match(repositoryInstructions, /`단계 완료`/)
  assert.match(repositoryInstructions, /`공개 준비 완료`/)
  assert.match(repositoryInstructions, /지적만으로 즉시 독립 검수를 다시 실행하지 않는다/)
  assert.match(mainDeveloperRole, /### 변경 유형별 기본 검증/)
  assert.match(mainDeveloperRole, /통과 항목 전체를 다시 실행하지 않고 P0·P1/)
  assert.match(designReviewRole, /### 검수 브리프/)
  assert.match(designReviewRole, /정상 응답을 확인한 URL·포트/)
  assert.match(designReviewRole, /사용자가 독립 재검수를 명시적으로 요청했거나/)
  assert.match(designReviewRole, /범위 검수는 브라우저 자동화가 중단되면 자동 재실행하지 않고/)
  assert.match(designReviewRole, /전체 검수는 30분 총시간 안에서 환경 정리 후 1회만 재시도/)
  assert.match(designReviewRole, /독립 재검토 없이 그 범위의 `보류`를 `조건부 통과`나 `통과`로 상향할 수 없다/)
  assert.match(designReviewRole, /이미 통과한 항목 전체를 반복 실행하지 않으며/)
  assert.match(designReviewChecklist, /### 범위 검수 프리셋/)
  assert.match(designReviewChecklist, /`component`/)
  assert.match(designReviewChecklist, /`flow`/)
  assert.match(designReviewChecklist, /`layer`/)
  assert.match(designReviewChecklist, /`motion`/)
  assert.match(designReviewChecklist, /범위 검수.*총시간은 10분을 넘기지 않는다/)
})
