import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const agentConfig = await readFile(new URL("../.codex/agents/design-reviewer.toml", import.meta.url), "utf8")
const repositoryInstructions = await readFile(new URL("../AGENTS.md", import.meta.url), "utf8")
const mainDeveloperRole = await readFile(new URL("../docs/MAIN_DEVELOPER_ROLE.md", import.meta.url), "utf8")
const requirements = await readFile(new URL("../docs/QUALITY_PORTAL_REQUIREMENTS.md", import.meta.url), "utf8")
const uiUxDesign = await readFile(new URL("../docs/UI_UX_DESIGN.md", import.meta.url), "utf8")
const designReviewRole = await readFile(new URL("../docs/DESIGN_REVIEW_AGENT.md", import.meta.url), "utf8")
const designReviewChecklist = await readFile(new URL("../docs/DESIGN_REVIEW_CHECKLIST.md", import.meta.url), "utf8")

test("영구 디자인 전문 검토 에이전트를 읽기 전용 프로젝트 설정으로 제공한다", () => {
  assert.match(agentConfig, /^name = "design_reviewer"$/m)
  assert.match(agentConfig, /^description = ".+"$/m)
  assert.match(agentConfig, /^sandbox_mode = "read-only"$/m)
  assert.match(agentConfig, /^model_reasoning_effort = "high"$/m)
  assert.doesNotMatch(agentConfig, /^model = /m)
  assert.match(agentConfig, /^developer_instructions = """$/m)
  assert.match(agentConfig, /코드, 설정, 문서와 테스트를 수정하지 않는다/)
  assert.match(agentConfig, /docs\/DESIGN_REVIEW_AGENT\.md의 "검토 절차"를 단일 기준으로 따른다/)
  assert.match(agentConfig, /docs\/DESIGN_REVIEW_CHECKLIST\.md를 따른다/)
  assert.doesNotMatch(agentConfig, /항상 다음 절차를 따른다/)
  assert.match(designReviewChecklist, /`기능 검증`, `범위 검수`, `전체 검수`를 선택한다/)
  assert.match(designReviewChecklist, /기능 검증에는 이 체크리스트와 디자인 전문 검토 에이전트를 적용하지 않는다/)
  assert.match(designReviewChecklist, /범위 검수.*총시간은 10분을 넘기지 않는다/)
  assert.match(designReviewChecklist, /전체 검수.*합계 30분을 넘기지 않는다/)
  assert.match(designReviewChecklist, /여러 기능을 함께 개발해도 기능 수만으로 전체 검수를 선택하지 않는다/)
  assert.match(designReviewChecklist, /\[범위·전체 기본\].*1920×1080 화면을 100% 배율과 DPR 1로 확인했다/)
  assert.match(designReviewChecklist, /\[조건부\].*1440×900이나 1366×768/)
  assert.match(designReviewChecklist, /\[모션·전환 변경 시\].*`prefers-reduced-motion: reduce` 환경/)
  assert.match(designReviewChecklist, /pseudo-element, 외곽 링, outline/)
  assert.match(designReviewChecklist, /내부 미니 화면은 같은 안전 영역/)
  assert.match(designReviewChecklist, /\[전역 내비게이션·레이어 변경 시\].*공통 헤더의 드롭다운·팝오버·툴팁을 실제로 열어/)
  assert.match(designReviewChecklist, /`elementsFromPoint\(\)` hit-test로 실제 최상단 표시를 검증했다/)
  assert.match(designReviewChecklist, /\[전역 내비게이션·레이어 변경 시\].*영향받는 전역 오버레이와 전체 화면 작업 영역의 교차 상태를 기록했다/)
  assert.match(designReviewChecklist, /목업 첨부파일처럼 실제 데이터가 없어 실행할 수 없는 조작은 무반응으로 끝나지 않고/)
  assert.match(agentConfig, /저장소 보고서는 직접 만들지 않고 구조화된 결과를 메인 개발자에게 반환한다/)
})

test("저장소 지침과 역할 문서가 영구 에이전트 사용 계약을 연결한다", () => {
  assert.match(repositoryInstructions, /\.codex\/agents\/design-reviewer\.toml/)
  assert.match(repositoryInstructions, /커스텀 에이전트 `design_reviewer`를 우선 사용/)
  assert.match(designReviewRole, /프로젝트 커스텀 에이전트 이름: `design_reviewer`/)
  assert.match(designReviewRole, /설정 파일: \[`.codex\/agents\/design-reviewer\.toml`\]/)
  assert.match(designReviewRole, /설정 파일의 존재는 에이전트 도입만 의미하며 실제 검토 완료를 의미하지 않는다/)
  assert.match(designReviewRole, /이 절은 디자인 전문 검토의 수행 순서를 정하는 단일 기준이다/)
  assert.match(designReviewRole, /### 0단계: 기능 검증/)
  assert.match(designReviewRole, /### 1단계: 범위 검수/)
  assert.match(designReviewRole, /### 2단계: 전체 검수/)
  assert.doesNotMatch(designReviewRole, /2단계 시작 전 기준선 검토/)
  assert.match(designReviewRole, /기능 개수, 변경 파일 수 또는 `전역`이라는 명칭만으로 승격하지 않는다/)
  assert.match(designReviewRole, /기준선·중간·최종 3회 검수는 전역 재설계처럼 장기간 진행되는 대형 디자인 작업에만 적용한다/)
  assert.match(designReviewRole, /범위 검수는 준비와 결과 정리를 포함해 10분을 상한/)
  assert.match(designReviewRole, /전체 검수는 30분 총시간 안에서/)
  assert.match(designReviewRole, /재시도가 별도의 추가 30분을 만들지 않는다/)
  assert.match(designReviewRole, /## 검수 기준 튜닝/)
  assert.match(designReviewRole, /일회성 내용은 해당 검토 보고서에만 기록하고, 재사용할 기준만/)
  assert.match(designReviewChecklist, /사용자 피드백으로 드러난 누락·오판·방향 불일치/)
  assert.match(designReviewRole, /독립 재검토 없이 그 범위의 `보류`를 `조건부 통과`나 `통과`로 상향할 수 없다/)
  assert.match(designReviewRole, /영향을 줄 때만 해당 근거를 `만료`로 표시/)
  assert.match(repositoryInstructions, /같은 화면의 여러 변경은 한 번의 범위 검수로 묶는다/)
  assert.match(repositoryInstructions, /사용자가 디자인 검수 제외 또는 범위를 명시하면 그 최신 요청을 우선/)
  assert.match(repositoryInstructions, /사용자가 검토 누락·오판·방향 불일치를 지적하면/)
  assert.match(mainDeveloperRole, /기능 검증, 범위 검수와 전체 검수를 구분한다/)
  assert.match(mainDeveloperRole, /누적 영향이 전체 검수 조건에 도달했을 때만 개발 종료 시 전체 검수 1회/)
  assert.match(requirements, /여러 기능은 영향받는 화면·업무 흐름별로 묶어 검수/)
  assert.match(uiUxDesign, /계산된 글자 크기 12px 이상/)
  assert.match(uiUxDesign, /일반 기능은 메인 개발자의 기능 검증/)
  assert.match(uiUxDesign, /자동 접근성 검사나 요소 본체의 사각형 측정만으로/)
})
