import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const html = await readFile(new URL("../prototype/index.html", import.meta.url), "utf8")
const script = await readFile(new URL("../prototype/app.js", import.meta.url), "utf8")
const styles = await readFile(new URL("../prototype/styles.css", import.meta.url), "utf8")
const qnaApp = await readFile(new URL("../prototype/src/qna/QnaApp.jsx", import.meta.url), "utf8")
const requirements = await readFile(new URL("../docs/QUALITY_PORTAL_REQUIREMENTS.md", import.meta.url), "utf8")
const developmentPlan = await readFile(new URL("../docs/DEVELOPMENT_PLAN.md", import.meta.url), "utf8")
const readme = await readFile(new URL("../README.md", import.meta.url), "utf8")
const phase2CompletionReport = await readFile(new URL("../docs/PHASE2_COMPLETION_REPORT.md", import.meta.url), "utf8")
const phase3CompletionReport = await readFile(new URL("../docs/PHASE3_COMPLETION_REPORT.md", import.meta.url), "utf8")

test("데이터 원천 관리 진입점을 제거하고 현재 요구사항에 기록한다", () => {
  assert.doesNotMatch(html, /data-planned="데이터 원천"/)
  assert.doesNotMatch(html, /<strong>데이터 원천<\/strong>/)
  assert.match(requirements, /포털 UI에 데이터 원천 관리 화면을 제공하지 않는다/)
})

test("통합 검색 팝업에서 Report, Rule&SOP, Q&A 콘텐츠로 연결한다", () => {
  assert.match(html, /data-global-search-open/)
  assert.match(html, /<dialog[^>]*data-global-search/)
  assert.match(html, /data-search-target="report"/)
  assert.match(script, /target: "rule"/)
  assert.match(html, /data-search-target="qna"/)
  assert.match(script, /const openGlobalSearch/)
  assert.match(script, /pendingGlobalSearchReportCard = card instanceof HTMLElement \? card : null/)
  assert.match(script, /setReportMode\("viewer", \{ card: pendingGlobalSearchReportCard, focus: false \}\)/)
  assert.match(script, /let focusFrames = 3/)
  assert.match(script, /window\.requestAnimationFrame\(focusReportViewer\)/)
  assert.match(script, /setRuleMode\("open", \{ focus: false \}\)/)
  assert.match(script, /setQnaMode\("open", \{ view: "detail", postId: contentId \}\)/)
  assert.match(qnaApp, /hasRequestedPost \? "detail" : "list"/)
  assert.match(styles, /\.header-search \{\s*min-width: 230px;/)
  assert.match(requirements, /검색 결과는 별도 팝업에 표시하고 선택한 Report, Rule&SOP 또는 Q&A 콘텐츠로 이동/)
})

test("마스터가 유저 ID와 소속부서 기준의 관리자·일반 접근 규칙을 관리한다", () => {
  assert.match(html, /data-user-workspace/)
  assert.match(html, /data-user-open/)
  assert.match(html, /data-access-add-open/)
  assert.match(html, /data-access-add-dialog/)
  assert.match(html, /data-access-field-input/)
  assert.match(html, /data-access-match-input/)
  assert.match(html, /data-access-value-input/)
  assert.equal([...html.matchAll(/data-access-role(?:\s|>)/g)].length, 2)
  assert.match(html, /value="admin"/)
  assert.match(html, /value="general"/)
  assert.match(html, /value="user-id"/)
  assert.match(html, /value="department"/)
  assert.match(html, /value="exact"/)
  assert.match(html, /value="contains"/)
  assert.match(html, /data-access-remove/)
  assert.equal([...html.matchAll(/data-access-row(?:\s|>)/g)].length, 4)
  assert.match(script, /const setUserMode/)
  assert.match(script, /document\.querySelector\("\[data-access-field-input\]"\)/)
  assert.match(script, /document\.querySelector\("\[data-access-match-input\]"\)/)
  assert.match(script, /const updateAccessCounts/)
  assert.match(script, /accessAddForm\?\.addEventListener\("submit"/)
  assert.match(script, /row\.dataset\.accessField === accessField/)
  assert.match(script, /row\.dataset\.accessMatch === accessMatch/)
  assert.match(requirements, /마스터, 관리자 또는 일반 권한으로 판정되지 않은 사용자는.*포털 화면에 접근할 수 없음/)
  assert.match(requirements, /더 높은 관리자 권한을 적용/)
})

test("확정한 역할별 콘텐츠와 Q&A 권한을 요구사항에 기록한다", () => {
  assert.match(requirements, /관리 대상 콘텐츠: Report, Rule&SOP, 변승위 Category/)
  assert.match(requirements, /\| 관리 대상 콘텐츠 \| 전체 조회·등록·수정·삭제 \| 전체 조회·등록·수정·삭제 \| 전체 조회 \|/)
  assert.match(requirements, /\| Rule&SOP \| 전체 조회·수정·삭제 \| 전체 조회·수정·삭제 \| 전체 조회 \|/)
  assert.match(requirements, /\| Q&A 답변·댓글 \| 전체 작성·수정·삭제 \| 전체 작성, 본인 작성분 수정·삭제 \| 전체 작성, 본인 작성분 수정·삭제 \|/)
  assert.match(requirements, /답변이 등록된 질문은 작성자가 수정할 수 있지만 삭제할 수 없으며, 마스터만 삭제 가능/)
  assert.match(requirements, /이전 상태를 포함해 자유롭게 변경 가능/)
  assert.match(requirements, /마스터가 1명뿐이면 해당 계정의 권한 회수를 비활성화/)
  assert.match(requirements, /Report와 Rule&SOP는.*각각 `report_reg`, `rulesop`에서 실제 삭제하고, Q&A 등 숨김 처리를 지원하는 콘텐츠는.*복구 가능한 숨김 처리로 수행하며 복구는 마스터만 가능/)
  assert.match(requirements, /콘텐츠·권한·Q&A 상태의 변경 이력은 마스터만 조회 가능/)
})

test("확정한 공통 화면 상태와 역할별 문의 대상을 문서에 기록한다", () => {
  assert.match(requirements, /로딩 시 대상 가까이에 회전형 아이콘과 처리 중 문구 표시/)
  assert.match(requirements, /데이터가 없으면 작은 비차단 팝업/)
  assert.match(requirements, /조회 오류 시 경고 아이콘, 오류 안내와 `다시 시도` 동작 제공/)
  assert.match(requirements, /실제 연동 전 목업 시각은 목업임을 명시/)
  assert.match(requirements, /권한이 없으면 일반유저는 관리자, 관리자는 마스터에게 문의/)
})

test("현재 로컬 가상 데이터와 운영 검증 경계를 요구사항에 기록한다", () => {
  assert.match(requirements, /현재 브라우저의 로컬 저장소에만 보관/)
  assert.match(requirements, /품질 Agent는 사내 RAG·GPT-OSS와 대화 DB를 Backend 흐름과 기존 UI에 연결/)
  assert.match(requirements, /Report 목록 조회·신규 등록·수정·실제 삭제는 `report_reg`에, Rule&SOP 목록 조회·수정·실제 삭제는 `rulesop`에 연결/)
  assert.match(requirements, /실제 SSO·Spotfire 인증·나머지 업무 DB·Parquet·공유 폴더 연동과 운영 보안·성능 검증은 후속 작업/)
  assert.match(developmentPlan, /별도 설명 없이 찾고 전체 사용 흐름을 체험할 수 있으며/)
})

test("사용자 및 권한 화면의 표와 조작 요소를 읽기 쉬운 크기로 제공한다", () => {
  const reportCardTitleSize = styles.match(/\.report-card-copy strong \{[^}]*font-size: (\d+px);/s)?.[1]
  const accessTableBodySize = styles.match(/\.user-table-row \{[^}]*font-size: (\d+px);/s)?.[1]

  assert.match(styles, /\.role-summary-card small \{[^}]*font-size: 14px;/s)
  assert.match(styles, /\.user-search input \{[^}]*font-size: 15px;/s)
  assert.match(styles, /\.admin-add-button \{[^}]*height: 48px;[^}]*font-size: 15px;/s)
  assert.match(styles, /\.user-table-header \{[^}]*min-height: 54px;[^}]*font-size: 14px;/s)
  assert.equal(accessTableBodySize, reportCardTitleSize)
  assert.match(styles, /\.access-value \{[^}]*font-size: 14px;/s)
  assert.match(styles, /\.access-role-badge \{[^}]*font-size: 14px;/s)
  assert.match(styles, /\.admin-remove-button \{[^}]*height: 44px;[^}]*font-size: 14px;/s)
  assert.match(styles, /\.admin-add-form > footer button \{[^}]*height: 46px;[^}]*font-size: 14px;/s)
})

test("품질 Agent UI와 실제 연동 경계를 요구사항에 명시한다", () => {
  assert.match(requirements, /기본 우측 대화 패널에서 사용하고 필요할 때 전체 작업 화면으로 확장/)
  assert.match(requirements, /RAG 검색, GPT-OSS 답변 생성과 MariaDB\/MySQL 대화 History를 Backend API로 연결/)
  assert.match(requirements, /실제 SSO 인증과 Report 참조 범위는 후속 연동에서 확정/)
})

test("현재 단계는 개발 계획을 단일 기준으로 삼고 완료 보고서는 당시 증거를 보존한다", () => {
  assert.match(developmentPlan, /현재 상태:\*\* 1단계 UI\/UX 설계 완료/)
  assert.match(developmentPlan, /2단계: UI 프로토타입 구현 · 완료/)
  assert.match(developmentPlan, /3단계: 로컬 기능 구현 · 부분 완료/)
  assert.match(developmentPlan, /현재 단계와 판정의 단일 기준/)
  assert.match(requirements, /단계별 현재 상태와 판정의 단일 기준은 \[개발 계획\]/)
  assert.doesNotMatch(requirements, /3단계 로컬 기능.*`부분 완료`/)
  assert.match(readme, /최신 단계·판정과 남은 검증은 \[개발 계획\]/)
  assert.match(developmentPlan, /125% 확대 검증은 사용자 결정으로 `해당 없음`/)
  assert.match(phase3CompletionReport, /125% 확대 검증은 사용자 결정으로 `해당 없음`/)
  assert.match(phase3CompletionReport, /`부분 완료`.*독립 디자인 게이트는 `보류`/)
  assert.match(phase3CompletionReport, /실행 당시의 증거 스냅샷/)
  assert.match(phase2CompletionReport, /실행 당시의 증거 스냅샷/)
  assert.match(phase3CompletionReport, /현재 브라우저에만 적용/)
  assert.match(phase2CompletionReport, /\*\*판정:\*\* `완료`/)
  assert.match(phase2CompletionReport, /실제 SSO, 데이터 원천, 문서 검색, Spotfire와 LLM 연동은 미구현/)
  assert.match(html, /예시 원천 상태/)
  assert.match(html, /사내 LLM · Backend 연결/)
  assert.doesNotMatch(html, /사내 LLM · 연동 예정/)
})
